- name: Copy files
  hosts: all
  vars:
    src: "{{ lookup('env', 'SRC') }}"
    dst: "{{ lookup('env', 'DST') }}"
    remote_src: false
    content: "{{ lookup('env', 'CONTENT') }}"
    
  tasks:
    - name: Copy file or directory to remote host
      copy:
        src: "{{ src }}"
        dest: "{{ dst }}"
        remote_src: false   # true if the src file or directory is on the remote host
#    - name: Write content to file on remote host
#      copy:
#        dst: "{{ dst }}"
#        content: {{ content }}
